-- 코드를 작성해주세요
# 1. 연도별 가장 큰 대장균 크기 구하기
# 2. 원본 테이블과 JOIN 
SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, (M.MAX_SIZE - E.SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM ECOLI_DATA E
JOIN (SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
        FROM ECOLI_DATA
        GROUP BY YEAR(DIFFERENTIATION_DATE)) M ON YEAR(E.DIFFERENTIATION_DATE)=M.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;

